default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: artillery_development
  username: postgres
  password: <%= Rails.application.credentials.dig(:db, :password) %>

test:
  <<: *default
  database: artillery_test
  username: postgres
  password: <%= Rails.application.credentials.dig(:db, :password) %>

production:
  <<: *default
  database: artillery_production
  username: postgres
  password: <%= Rails.application.credentials.dig(:db, :password) %>
